let shopItemsData = [
    {
      id: "jfhgbvnscs",
      name: "Group T-Shirt",
      price: 45,
      desc: " Japanese lifestyle and culture.",
      img: "images/img-1.jpg",
    },
    {
      id: "ioytrhndcv",
      name: "Lulka T-shirt",
      price: 50,
      desc: " Japanese lifestyle and culture.",
      img: "images/img-2.jpeg",
    },
    {
      id: "wuefbncxbsn",
      name: "Dragon Ball",
      price: 25,
      desc: " Japanese lifestyle and culture.",
      img: "images/img-3.jpg",
    },
    {
      id: "thyfhcbcv",
      name: "GOJO",
      price: 60,
      desc: " Japanese lifestyle and culture.",
      img: "images/img-4.jpg",
    },
    {
      id: "thiecbawdjksadjk",
      name: "NINJA",
      price: 35,
      desc: " Japanese lifestyle and culture.",
      img: "images/img-5.jpg",
    },
    {
      id: "iuertrywebncdjksadjk",
      name: "CLASH-TITANS",
      price: 60,
      desc: " Japanese lifestyle and culture.",
      img: "images/img-6.jfif",
    },
    {
      id: "thierytbvcbvzdhadjk",
      name: "Hunter Killua",
      price: 65,
      desc: " Japanese lifestyle and culture.",
      img: "images/img-7.jfif",
    },
    {
      id: "trfoiwfcnbcawdjksadjk",
      name: "Death note",
      price: 70,
      desc: " Japanese lifestyle and culture.",
      img: "images/img-8.jpg",
    },
    {
      id: "cbvxbcvsceldk",
      name: "Cacyo",
      price: 43,
      desc: " Japanese lifestyle and culture.",
      img: "images/img-9.jfif",
    },
    {
      id: "oiopijmjkhuihb",
      name: "Killua Zoldyck",
      price: 75,
      desc: " Japanese lifestyle and culture.",
      img: "images/img-10.jpeg",
    },
    {
      id: "oiopijewyiohbjhib",
      name: "Naruto",
      price: 35,
      desc: " Japanese lifestyle and culture.",
      img: "images/img-11.jpeg",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Fruado",
      price: 35,
      desc: " Japanese lifestyle and culture.",
      img: "images/img-12.jpg",
    },
  ];